/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Controller;
import domain.MeasurementUnit;
import domain.Product;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import tables.ProductTableModel;


/**
 *
 * @author Korisnik
 */
public class FormProductSearch extends javax.swing.JDialog {
    
    

    /**
     * Creates new form FormProductSearch
     */
    public FormProductSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        
        fillForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        tblProductSearch = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search");

        tblProductSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "MeasurementUnit", "Price with VAT", "Price without VAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane.setViewportView(tblProductSearch);

        btnDetails.setText("Details...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetails))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDetails)
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnDetails;
    private javax.swing.JTable tblProductSearch;
    // End of variables declaration//GEN-END:variables

    private void fillForm() {
        
        List<Product> products = Controller.getInstance().getAllProducts();
        
        TableModel tm = new ProductTableModel(products);
        tblProductSearch.setModel(tm);
        //Ne mogu da promenim celije ostale koje sam htela
       
        
        
        MeasurementUnit[] measurementUnits = new MeasurementUnit[]{MeasurementUnit.KG,MeasurementUnit.L,MeasurementUnit.PCS};
        JComboBox comboMeasurementUnits = new JComboBox(new DefaultComboBoxModel(measurementUnits));
        
        TableColumn tc = tblProductSearch.getColumnModel().getColumn(3);
        tc.setCellEditor(new DefaultCellEditor(comboMeasurementUnits));
        
    }
}

