/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Controller;
import domain.MeasurementUnit;
import domain.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FormNewProduct extends javax.swing.JDialog {
    private Controller controller;
    /**
     * Creates new form FormNewProduct
     */
    public FormNewProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        fill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        cbMeasurementUnit = new javax.swing.JComboBox<>();
        txtPriceWithVAT = new javax.swing.JTextField();
        txtPriceWithoutVAT = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Product");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/form/pozadina.png"))), "New product", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel2.setText("Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel3.setText("Quantity:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel4.setText("MeasurementUnit:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel5.setText("Price with VAT:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel6.setText("Price without VAT:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 50, -1));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 120, -1));
        jPanel2.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, -1));

        jPanel2.add(cbMeasurementUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 60, -1));
        jPanel2.add(txtPriceWithVAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, -1));
        jPanel2.add(txtPriceWithoutVAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 80, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 390, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        int id = Integer.parseInt(txtID.getText());
        String name = txtName.getText().trim();
        int quantity = Integer.parseInt(txtQuantity.getText());
        MeasurementUnit measurementUnit = (MeasurementUnit) cbMeasurementUnit.getSelectedItem();
        double priceWithVAT = Double.parseDouble(txtPriceWithVAT.getText());
        double priceWithoutVAT = Double.parseDouble(txtPriceWithoutVAT.getText());
        
        
        
        Product product = new Product(id, name, quantity, measurementUnit, priceWithVAT, priceWithoutVAT);
        Controller.getInstance().saveProduct(product);
        JOptionPane.showMessageDialog(this, "Product is save!");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<MeasurementUnit> cbMeasurementUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPriceWithVAT;
    private javax.swing.JTextField txtPriceWithoutVAT;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void fill() {
        cbMeasurementUnit.removeAllItems();
        cbMeasurementUnit.addItem(MeasurementUnit.KG);
        cbMeasurementUnit.addItem(MeasurementUnit.L);
        cbMeasurementUnit.addItem(MeasurementUnit.PCS);
    }
}
