package form;

import controller.Controller;
import domain.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import session.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Korisnik
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblPozadina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caffe poslasticarnica Bojana");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setForeground(new java.awt.Color(255, 0, 51));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 210, 30));

        lblPassword.setFont(new java.awt.Font("HelveticaNeueLT Pro 33 ThEx", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 120, -1));

        lblUsername.setFont(new java.awt.Font("HelveticaNeueLT Pro 33 ThEx", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username:");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 30));

        lblError.setBackground(new java.awt.Color(255, 0, 0));
        lblError.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 210, -1));

        pfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));
        jPanel1.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 210, 30));

        btnLogin.setFont(new java.awt.Font("HelveticaNeueLT Pro 33 ThEx", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 0, 51));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(255, 102, 102), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 51, 51)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 150, 40));

        lblPozadina.setFont(new java.awt.Font("HelveticaNeueLT Pro 43 LtEx", 0, 14)); // NOI18N
        lblPozadina.setForeground(new java.awt.Color(255, 255, 255));
        lblPozadina.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korisnik\\Desktop\\fax IV godina\\Softveri\\aplikacija.png")); // NOI18N
        lblPozadina.setText("Username");
        jPanel1.add(lblPozadina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String username = txtUsername.getText().trim();
        String password = new String(pfPassword.getPassword());
        
        if(!username.isEmpty() && !password.isEmpty() ){
        try {
            User user = Controller.getInstance().login(username, password);
            Session.getInstance().setCurrentUser(user);
            
            
            JFrame formMain = new FormMain();
            formMain.setVisible(true);
            this.dispose();
        
        } catch (Exception ex) {
            lblError.setText(ex.getMessage());
        }
        }
        else{
            lblError.setText("Username or password is empty");
        }
        
        


    }//GEN-LAST:event_btnLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPozadina;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
